name: build single windows server
inputs:
  solution:
    required: true
  configuration:
    required: true
  platform:
    required: true
  installer:
    required: true
  upload_url:
    required: true
  asset_path:
    required: true
  asset_name:
    required: true
  token:
    required: true
runs:
  using: "composite"
  steps:
    - name: build
      shell: pwsh
      working-directory: ./.mainrepo
      run: msbuild "${{ inputs.solution }}" -t:rebuild -property:Configuration="${{ inputs.configuration }}" -property:Platform="${{ inputs.platform }}"

    - name: installer
      shell: pwsh
      working-directory: ./.mainrepo
      run: msbuild "${{ inputs.installer }}"

    - name: upload
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ inputs.upload_url }}
        asset_path: ./.mainrepo/${{ inputs.asset_path }}
        asset_name: ${{ inputs.asset_name }}
        asset_content_type: application/octet-stream
      env:
        GITHUB_TOKEN: ${{ inputs.token }}