name: build single windows server
inputs:
  installer:
    required: true
  upload_url:
    required: true
  asset_path:
    required: true
  asset_name:
    required: true
  token:
    required: true
  pfx:
    required: true
  password:
    required: true
runs:
  using: "composite"
  steps:
    - name: installer
      shell: pwsh
      working-directory: ./.mainrepo
      run: msbuild "./installer/engine.all/${{ inputs.installer }}" "/p:PFX=${{ inputs.pfx }}" "/p:PWD=${{ inputs.password }}"

    - name: upload
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ inputs.upload_url }}
        asset_path: ./.mainrepo/${{ inputs.asset_path }}
        asset_name: ${{ inputs.asset_name }}
        asset_content_type: application/octet-stream
      env:
        GITHUB_TOKEN: ${{ inputs.token }}