name: sign module
inputs:
  path:
    required: true
  pfx:
    required: true
  password:
    required: true
runs:
  using: "composite"
  steps:
    - name: find signtool
      id: st
      shell: pwsh
      run: |
        $list = Get-ChildItem -Path "C:/Program Files (x86)/Windows Kits/10/bin/*/x64/signtool.exe"
        echo "::set-output name=SIGNTOOL::$($list[-1].FullName)"

    - name: create PFX file
      shell: pwsh
      run: |
        $pfxData = [System.Convert]::FromBase64String("${{ inputs.pfx }}");
        $pfxData | Set-Content -Path ".pfx" -AsByteStream

    - name: sign
      shell: cmd
      run: "${{ steps.st.outputs.SIGNTOOL }}" sign /f ".pfx" /p "${{ inputs.password }}" /fd SHA256 "${{ inputs.path }}"

    - name: delete PFX file
      shell: cmd
      run: del ".pfx"