name: build linux servers

#on:
#  release:
#    types: [created]
on: 
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        repository: "x-tensive/open62541-servers"
        ref: "master"
        submodules: recursive
        token: ${{ secrets.BUILDER_TOKEN }}
        
    - name: update version
      shell: pwsh
      # run: ./.buildtools/github/updateVersion.ps1 "${{ github.event.release.tag_name }}"
      run: ./.buildtools/github/updateVersion.ps1 "v3.4.5"
      
    - name: build
      run: |
        rm -Rf "./.out/sinumerik/x64.Release S7TCP"
        mkdir -p "./.out/sinumerik/x64.Release S7TCP"
        cd "./.out/sinumerik/x64.Release S7TCP"
        cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_ARCHITECTURES=x86_64 ../../../ua_sinumerikServer
        cmake --build .
      
#    - name: upload FANUC FOCAS - x64
#      uses: actions/upload-release-asset@v1
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      with:
#        upload_url: ${{ github.event.release.upload_url }} 
#        asset_path: ./.out/installer/focas.x64/dpa.ua.focas.install64.exe
#        asset_name: dpa.ua.focas.install64_${{ github.event.release.tag_name }}.exe 
#        asset_content_type: application/octet-stream
