name: build windows servers

on:
  workflow_dispatch:
    inputs:
      version:
        description: release version
        default: "github.event.inputs.name"
        required: true

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        repository: "x-tensive/open62541-servers"
        ref: "master"
        submodules: recursive
        token: ${{ secrets.BUILDER_TOKEN }}
    - name: add msbuild
      uses: microsoft/setup-msbuild@v1.1
    - name: build SINUMERIK S7 ONLINX XPSP3
      run: msbuild ua_sinumerikServer/ua_sinumerikServer_onlinx.sln -t:rebuild -property:Configuration="Release XPSP3" -property:Platform=x86
    - name: build SINUMERIK S7 ONLINX W2K
      run: msbuild ua_sinumerikServer/ua_sinumerikServer_onlinx.sln -t:rebuild -property:Configuration="Release W2K" -property:Platform=x86
