name: Manual workflow

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Person to greet'
        default: 'v0.0.0'
        required: true
jobs:
  createRelease:
    runs-on: ubuntu-latest
    steps:
    - uses: ncipollo/release-action@v1
      with:
        repo: open62541-servers
        owner: x-tensive
        tag: ${{ github.event.inputs.version }}
        name: Release ${{ github.event.inputs.version }}
        commit: master
        draft: false
        prerelease: false
        token: ${{ secrets.BUILDER_TOKEN }}
