name: Build windows servers

on:
  workflow_dispatch:
    inputs:
      version:
        description: release version
        default: "github.event.inputs.name"
        required: true

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        repository: "x-tensive/open62541-servers"
        ref: "master"
        submodules: recursive
        token: ${{ secrets.BUILDER_TOKEN }}
