name: Manual workflow

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Person to greet'
        default: 'v0.0.0'
        required: true
jobs:
  createRelease:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.BUILDER_TOKEN }}
      with:
        repo: open62541-servers
        owner: x-tensive
        tag_name: ${{ github.event.inputs.version }}
        release_name: Release ${{ github.event.inputs.version }}
        commitish: main
        draft: false
        prerelease: false
