name: Build windows servers

on:
  workflow_dispatch:
    inputs:
      version:
        description: release version
        default: "github.event.inputs.name"
        required: true

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: set git secret for open62541-MI
      run: gh secret set "STACK" --repo "x-tensive/open62541-MI" -app "actions"
      env:
        GH_TOKEN: ${{ secrets.OPEN62541_STACK_KEY }}
    - name: checkout
      uses: actions/checkout@v3
      with:
        repository: "x-tensive/open62541-servers"
        ref: "master"
        submodules: recursive
        ssh-key: ${{ secrets.OPEN62541_SERVERS_KEY }}
