name: build dpa.opcua.rs

on: 
  workflow_dispatch:
    inputs:
      version:
        description: "version"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout local
      uses: actions/checkout@v3
      with:
        path: "./.localrepo"
    - name: checkout
      uses: actions/checkout@v3
      with:
        repository: "x-tensive/open62541-servers"
        ref: "master"
        submodules: false
        token: ${{ secrets.BUILDER_TOKEN }}
        path: "./.mainrepo"
        
    - name: update version
      uses: actions/github-script@v6
      with:
        script: |
          const updateVersion = require("./.localrepo/.github/scripts/updateCsprojVersion");
          updateVersion("./.mainrepo/tools/rs/rs.csproj", "${{ inputs.version }}");

    - name: add dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
    
    - name: build dpa.opcua.rs
      run: dotnet build --configuration Release ./.mainrepo/tools/rs/rs.sln
    
    - name: zip assets
      run: zip -r dpa.opcua_${{ inputs.version }}.zip ./.mainrepo/tools/rs/bin/Release/net6.0
    
    - name: upload
      uses: actions/upload-release-asset@v1
      with:
        upload_url: https://uploads.github.com/repos/x-tensive/OPCUA.embedded/releases/81196678/assets{?name,label}
        asset_path: dpa.opcua_${{ inputs.version }}.zip
        asset_name: dpa.opcua_${{ inputs.version }}.zip
        asset_content_type: application/octet-stream
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}