name: release main repo

on:
  release:
    types: [ "released" ]

jobs:
  createRelease:
    runs-on: ubuntu-latest
    steps:
    - uses: ncipollo/release-action@v1
      with:
        repo: open62541-servers
        owner: x-tensive
        tag: ${{ github.event.release.name }}
        name: ${{ github.event.release.name }}
        commit: master
        draft: false
        prerelease: false
        token: ${{ secrets.BUILDER_TOKEN }}
