name: code sign test

on:
  workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: find signtool
      id: st
      shell: pwsh
      run: |
        $list = Get-ChildItem -Path "C:/Program Files (x86)/Windows Kits/10/bin/*/x64/signtool.exe"
        echo ::set-output signtool=$($list[-1].FullName)
    
    - name: create PFX file
      shell: pwsh
      run: |
        $pfxData = [System.Convert]::FromBase64String("${{ secrets.CODESIGN_CERT_BASE64 }}");
        $pfxData | Set-Content -Path ".pfx" -Encoding byte
    
    - name: output
      run: |
        ls
        echo ${{ steps.st.outputs.signtool }}