name: code sign test

on:
  workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: checkout local
      shell: pwsh
      run: ls "C:/Program Files (x86)/Windows Kits/10/bin/*/x86/sign*.*"