name: update-wiki-links

on:
  release:
    types: [ "released" ]

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
#      - name: checkout
#        uses: actions/checkout@v3
#        with:
#          repository: x-tensive/OPCUA.embedded.wiki
      - name: echo
        run: |
          echo ${{ github.ref }}
          echo ${{ github.ref_name }}
          echo ${{ github.ref_type }}
      - name: assets
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release view ${{ github.ref }} -R ${{ github.repository }}

