name: update-wiki-links

on:
  release:
    types: [ "released" ]

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          repository: https://github.com/x-tensive/OPCUA.embedded.wiki.git
